[package]
name = "awful_aws_sample"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.47.0"
rusoto_sqs = "0.47.0"
structopt = "0.3.22"
tokio = { version = "1", features = ["full"] }